services:
  backend:
    build: ./backend
    ports:
      - "8050:8050"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: f1_league
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql



volumes:
  db_data: