# Usa la imagen base de PHP
FROM php:8.2-cli

# Instalar dependencias necesarias para Composer
RUN apt-get update && apt-get install -y \
    curl \
    libzip-dev \
    unzip \
    && docker-php-ext-install zip

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Copiar los archivos del backend al contenedor
COPY . .

# Ejecutar Composer para instalar dependencias
RUN composer install

# Comando para iniciar el servidor PHP
CMD php -S 0.0.0.0:8050 -t public